import { Inter } from 'next/font/google'
import './globals.css'

import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
    <head>
      <Script
        async
        src="https://www.googletagservices.com/tag/js/gpt.js"
      />

      <Script id="show-banner">
        {` var googletag = googletag || {}; googletag.cmd = googletag.cmd || [];`}
      </Script>
    </head>

    <body className={inter.className}>{children}</body>
    </html>
  )
}
